### ISSUE TITLE
filter field

### ISSUE THREAD

**Issue by tlhpray** [lxde/pcmanfm-qt#131]
I would see it under address field, in same line as "places" word, or above status bar at the bottom with ability to turn it on/off in settings or on main toolbar. This filter field would be basically find in current directory (without subfolders) with results in folder window. Later it can be enhanced as universal find tool giving it 2 icon options at the end of the field. One, lock filter when changing directories; two, settings where you can point where to look, with or without subfolders, what type of files, etc. typical finding options). It will greatly enhance searching/dealing with multiply files as currently pcmanfm-qt really lacks in this area (no search tool and filters).

**Comment by stefonarch** [comment]
Seems on a good way:
https://github.com/lxde/pcmanfm-qt/pull/229

**Comment by tsujan** [comment]
Although it's easy to implement a show/hide button for the filterbar at #229, I don't think it's needed because if the user uses it for a while, he'll find it indispensable.
Turning a filterbar into a universal search tool would undermine its usability and PCMan has already added a good search utility.
I agree about a lock button. Maybe later.

**Comment by PCMan** [comment]
Well, we already have the filter bar and there's an option to turn if off.
