### ISSUE TITLE
pcmanfm-qt does not follow lxqt theme

### ISSUE THREAD

**Issue by ArthurBorsboom** [lxde/pcmanfm-qt#141]
I am unsure what the intented way is how pcmanfm-qt should be themed, however it does not seem to use my chosen "Ambient" lxqt theme.

Should pcmanfm-qt follow the lxqt theme?
If not, what is the recommended way of theming?

**Comment by pmattern** [comment]
To my knowledge the effect of themes as set in LXQt Appearance Configuration (binary lxqt-config-appearance) - 'LXQt Theme' (left column) regarding application windows is very limited, e. g. icons in icon bars are handled by icon themes, windows' title bars by window managers. In fact I didn't see any effect of changing icon themes regarding PCManFM-Qt so far at all.
Also, there was an issue regarding file monitoring recently that affected realizing changed settings as well, see e. g. https://github.com/lxde/lxqt/issues/441 or https://github.com/lxde/lxqt/issues/351.
So chances are what you're seeing is related to one of these items, imo.

Otherwise I think it would be good to know what exactly your findings regarding PCManFM-Qt look like.
Also, some information about your system - architecture, distribution and so on - would be helpful.

**Comment by pmattern** [comment]
@ArthurBorsboom 
Any chance to have another look at this?

**Comment by ArthurBorsboom** [comment]
Changing the lxqt theme does have direct effect on the lxqt-panel.
Maybe I should have asked the question differently, like this.

What theme or setting do I need to change to have pcmanfm-qt to the same orange/dark gray colors of the Ambient theme, preferably a black background instead of the bright white one.

![2015-06-12-222511_960x618_scrot](https://cloud.githubusercontent.com/assets/6639859/8139188/ef3ca904-1151-11e5-8acf-5c448623a9d5.png)

**Comment by PCMan** [comment]
There is no way to do this at the moment.
lxqt-panel is themed using its own qss style.
Other Qt apps just use the default Qt theme engine.
It's not a bug. It's the limitation of Qt.

**Comment by baptx** [comment]
@PCMan Has there been a workaround since 2015? If it is not possible to do it because of Qt, it would be nice to include a dark theme in the settings like Firefox or Thunderbird are doing.

**Comment by tsujan** [comment]
FYI:

This report was opened based on a misunderstanding, which was found soon and led to its closing.

Qt apps should be styled by the active Qt widget style. That's an important part of "platform integration". The same is true for GTK apps under GTK DEs. Adding codes to an app for it to have a separate style not only is a big overkill but also breaks platform integration.

Of course, *special* apps like panel can be exceptions to this rule, which is respected by all DEs (KDE, GNOME,...).

**Comment by baptx** [comment]
@tsujan I just found an article with the solution I was looking for to use the system theme in Qt apps, using the tool you made Kvantum which could help other people finding this GitHub issue: https://www.linuxuprising.com/2018/05/use-custom-themes-for-qt-applications.html
It works well and now I can use pcmanfm-qt with a dark theme. I just noticed 2 issues when using Kvantum on Lubuntu 20.04 that are maybe fixed in a newer version of LXQt:
- the desktop background can be drag and dropped and then when we move a window over the empty area, it draws the content we moved over.
- the LXQt theme Frost now uses a white color instead of black, so I have to select another theme like Dark (which also uses a red color but I preferred the blue color from Frost).

**Comment by tsujan** [comment]
> the desktop background can be drag and dropped

Kvantum can't do that. Lubuntu may have an outdated version of it. Anyway, bug reports against Kvantum should be made at https://github.com/tsujan/Kvantum/issues.

> the LXQt theme Frost now uses a white color instead of black in the panel

Frost is supposed to invert the colors; that's its feature. It's dark with light themes and light with dark ones. There are other LXQt themes that are always dark but still, I don't know if they exist in Lubuntu.

This report wasn't about styling Qt apps, which was always possible. It was about applying LXQt themes to all apps, which is impossible.

However, the next release of LXQt (1.1.0) comes with pre-defined palettes that match some LXQt themes. The user could apply them in LXQt Appearance Configuration with Fusion (Qt's default style). Sadly, Lubunu is usually one version behind the latest LXQt release.
