### ISSUE TITLE
File manager actions do not work

### ISSUE THREAD

**Issue by Vladimir-csp** [lxde/pcmanfm-qt#155]
pcmanfm-qt 0.9.0
I'm trying to test file manager actions with this test action:

```
[Desktop Entry]
Name=Test action
Tooltip=Test actions
Icon=terminal
Profiles=on_folder;on_file;

[X-Action-Profile on_folder]
Name=Test action profile
MimeTypes=inode/directory;
SelectionCount=1
Schemes=file;
Exec=zenity --info --text=%f

[X-Action-Profile on_file]
Name=Test action profile
MimeTypes=text/plain;
SelectionCount=1
Schemes=file;
Exec=zenity --info --text=%f
```

It correctly matches files and dirs for action, but running the action does nothing.
Console output when triggering action:

```
** (pcmanfm-qt:32455): CRITICAL **: fm_file_action_item_launch: assertion 'ctx != NULL' failed
```

**Comment by cipricus** [comment]
This also affects version 0.10.0

**Comment by pmattern** [comment]
Running lxde/libfm-qt@e3e2839 and lxde/pcmanfm-qt@1d38bbd on Arch Linux the custom action posted above launches a dialogue window that is stating the absolute path of the object in question and that can be closed by a button "OK". The only weirdness was the dialogue wasn't placed in the foreground when PCManFM-Qt was launched from xterm in an Openbox ("only" / no LXQt) session, but even this ceased when it was launched from QTerminal instead.
I have never used zenity so far but doesn't this pretty much look like the expected behaviour? And if so, any chance you can verify running more recent versions of LXQt?

@cipricus
While I understand the problem may represent an annoyance for you release 0.10 has to be considered as seriously outdated by now and it's rather pointless for us to try and track issues it may have had.
You may want to have a look at the [instructions](https://github.com/lxde/lxqt/wiki/Building-from-source) to build latest VCS checkouts from source. These don't involve binary packages but do work on all major Linux distributions.

**Comment by tsujan** [comment]
Definitely not an issue anymore, after so many changes to libfm-qt. I have many file manager actions and all of them work correctly.
