### ISSUE TITLE
Kate opens text file as a "new file" upon double click

### ISSUE THREAD

**Issue by ms6676749** [lxde/pcmanfm-qt#288]
Archlinux
PCManFM 0.10.0

`$xdg-open foo` works fine opening up the text file in kate as is.  Other programs open up the text file just fine (right click file > open with >): Libreoffice Writer, Calligra Words, notepad (win).  Using "open with" with kate yielded the same buggy result (blank page, see below).

Observed Behavior (where txt files are associated with kate):
1) Open pcmanfm-qt
2) Go to any text file and doubleclick it.
3) Kate opens to a blank page with "New File" pop-up message showing on the upper right hand side of the document.

Expected Behavior:
1) Open pcmanfm-qt
2) Go to any text file and doubleclick it.
3) Kate, the associated program here, should open it displaying the text file contents as is.

**Comment by pmattern** [comment]
Confirmed as described above.

Same finding with KWrite (for the sake of completeness, not exactly a surprise). Filename gets displayed in document tab of Kate / titlebar of KWrite as usual. Nothing helpful in systemd journal.

Problem is apparently due to Kate / KWrite stating placeholder ("field code") `%U` in the `Exec` line of their desktop entry files `*.desktop`.
It ceases if `%U` gets replaced with `%f` or `%F`. Also, while some editors like [medit](http://mooedit.sourceforge.net/) or Leafpad are working flawlessly using placeholder `%U` (replacing `%{F,f}` in their stock desktop entry files) both gvim and [vim-Qt / qvim](https://bitbucket.org/equalsraf/vim-qt) are given trouble by `%U` as well. They throw a warning `W13: Warning: File "<filename>" has been created after editing started` and if the message is confirmed by hitting `Ok` a blank document is opened, too.
So maybe related to lxde/lxqt#921?

**Comment by tsujan** [comment]
I had a similar issue with my Qt text editor and  pcmanfm-qt when file names had special characters in them and, as a workaround, I used `%F` instead of `%U` in the desktop file. I don't think the problem is in Kate or my text editor because both work OK with Dolphin and other file managers I know of when `%U` is used.

GTK-based apps like Firefox use `%u` and have no problem with pcmanfm-qt. The root of the problem may be in libfm, which isn't Qt-based.

**Comment by paulolieuthier** [comment]
@tsujan you are probably right. The GTK-based PCManFM also has this problem.

**Comment by tsujan** [comment]
So, I was right about libfm but NOT about its Qt-independence being the root ;)

**Comment by ms6676749** [comment]
@tsujan Actually, this issue occurred with the following filenames: `1_useful_commands` (a symlink) and `~/Remove.txt`, the latter of which was in my home directory and hardly contained any special characters.  However, I tried what you suggested and it it appears to be a suitable workaround: `right click > Open with > other applications > (find and select kate) > custom command tab > kate %f > appllication name, i.e. Kate (text) > set as default`  

To be honest, I never experienced this issue with kate on pcmanfm-qt the past few months I've been using it as my default fm.  Strange that some KDE programs like kwrite experience this issue (confirmed here) and others like krita and okular do not.

**Comment by tsujan** [comment]
> ... the latter of which was in my home directory and hardly contained any special characters.

So, the situation may be more complex. There may be a problem in libfm and/or in Qt5. All I know is that `%U` doesn't work OK with special characters -- not even in fm custom actions -- while `%F` and `%f` do.

**Comment by tsujan** [comment]
This should be related to #155. The vala part of libfm is a mystery to me. Only @PCMan could fix it.

**Comment by goetzc** [comment]
I can add that: 
* kate -b %U  doesn't work (the default). 
* kate -b %F  does work.

It seems that pcmanfm-qt appends the `file:` prefix, like file:/home/user/. Sometimes I also see the path /home/user/File:main.txt when opening the embedded terminal in Kate

**Comment by YamashitaRen** [comment]
Wow. Here kate %f works but kwrite %f doesn't work...

**Comment by RalfJung** [comment]
This is a bug in Kate, and should be closed here: <https://bugs.kde.org/show_bug.cgi?id=363297>
