### ISSUE TITLE
Navigation icons don't get mirrored in RTL layout

### ISSUE THREAD

**Issue by SafaAlfulaij** [lxde/pcmanfm-qt#305]
In RTL layouts (such as Arabic), navigation arrows (Go Forward/Back and Go) doesn't get mirrored. 
![pcmanfmqticonmirroring](https://cloud.githubusercontent.com/assets/3509617/12745613/45fae0e6-c9ab-11e5-8110-ce1f4dc73911.png)

**Comment by SafaAlfulaij** [comment]
Ping?

**Comment by tsujan** [comment]
Sorry! I'll look into it.

**Comment by tsujan** [comment]
Are all other icons OK for RTL (tab righ-click menu with multiple tabs, for example)?

**Comment by tsujan** [comment]
@SafaAlfulaij 
Please test https://github.com/lxde/pcmanfm-qt/pull/366 if you compile from the source! I could just use the `-reverse` flag to test it.

**Comment by SafaAlfulaij** [comment]
I tested it and didn't work, flipped the two icon variables in the source code and didn't work either. Something is wrong with my configuration...
So, In case that they are mirrored with "-reverse", you can close the bug.
Thanks!

**Comment by tsujan** [comment]
> I tested it and didn't work...

Did you stop the desktop process before testing?

![rtl](https://cloud.githubusercontent.com/assets/981076/16265718/2f585a3a-3896-11e6-9f39-30251730e538.png)

**Comment by SafaAlfulaij** [comment]
Yes of course..
Anyway, it looks fine. But is it possible to mirror the other icons? It's just QIcon -> QPixmap -> QImage -> mirrored function -> QPixmap -> QIcon :blush:
Not all the icons, but the ones that are in the toolbar (New tab, Refresh and go) and "New folder" in the menu. Others won't be easily recognized that they aren't mirrored.

Thanks a lot!

**Comment by tsujan** [comment]
@SafaAlfulaij 
Mirroring is possible but what isn't -- it wouldn't be worth the effort or the amount of code that should be added. Moreover, it wouldn't make much sense either because the other icons are good for RTL and if an RTL user wants different icons, he/she could use other icon sets or edit the current one.

Anyway, I don't understand why https://github.com/lxde/pcmanfm-qt/pull/366 didn't work for you while it works with `-reverse` and even with an on-the-fly change in the layout direction.

**Comment by SafaAlfulaij** [comment]
Got it to work! (Somehow)
Thanks. It's ok leaving the others.
