### ISSUE TITLE
bug: menubar visible again after reboot

### ISSUE THREAD

**Issue by excalibur1234** [lxde/pcmanfm-qt#327]
i usually always try to hide the menubar.
but i have always seen the menubar again after a reboot.

it is possible this bug is related to #326, then there is another bug: pcmanfm-qt crashes after every logoff or before every boot.
if this bug is not related to #326, then this is a separate bug.

**Comment by pmattern** [comment]
Figuring out whether or not a crash is involved should be rather easy by looking through systemd journal.
E. g. `journalctl -b0` to view the logs since last boot, `journalctl --since='2016-03-10 08:20'` to view since the time stamp stated or `journalctl --follow --full` to watch in real-time, eventually invoked from a virtual terminal to be independent of the LXQt session.

**Comment by excalibur1234** [comment]
thanks for the tips for journalctl. i have saved them.

it looks like pcmanfm-qt does not crash during poweroff or reboot and at boot. i have checked it for lxqt and pcmanfm, but there are no entries for pcmanfm. there are a couple of entries for lxqt (mainly lxqt-connman-applet and lxqt-policykit).


the whole situation is really strange: every time i rebuild lxqt (including pcmanfm) and reboot, everything works very well. until a crash (or a reboot?), then keyboard shortcuts stop working, etc (see #326).

**Comment by excalibur1234** [comment]
this issue seems resolved. 
the menubar stays hidden now even after a reboot.
