### ISSUE TITLE
Find Files "The specified location is not supported."

### ISSUE THREAD

**Issue by r-a-v-a-s** [lxde/pcmanfm-qt#354]
No matter what I add as the "Place to search" when I try to run the search it says:

> The specified location is not supported.

Version 0.10.0

OpenSUSE Tumbleweed

**Comment by pmattern** [comment]
I can confirm the problem running PCManFM-Qt from repo `X11:LXQt` on openSUSE Leap 42.1. But it ceases when [PCManFM-Qt 0.10.0](https://github.com/lxde/pcmanfm-qt/releases) gets compiled on the same system using all dependencies as provided by the distribution. Also, the problem cannot be seen running PCManFM-Qt 0.10.0 on Arch Linux or Fedora where the version of Arch Linux was definitely not patched to mitigate any problem like the one discussed here.
So this is obviously a downstream packaging problem. Not the first time, unfortunately, see comment of user "cornelisbb" at https://build.opensuse.org/project/show/X11:LXQt. So @jubalh or one of the other openSUSE maintainers should really have a look. Otherwise you may report the problem on the [openSUSE issue tracker](https://bugzilla.opensuse.org).

In case you want to reproduce the needed dependencies are
```
# zypper install libqt5-qtbase-devel libqt5-qttools-devel libqt5-qtx11extras-devel glib2-devel libfm-devel menu-cache-devel
```
and simply running `cmake -DCMAKE_INSTALL_PREFIX=/usr`, `make` and `make install` as usual will do.

Additional notes:
The problem seems related to glibc. After noticing the message was still in the system locale German when LXQt was configured to display in English I looked through the translations of glib and indeed [this string](https://git.gnome.org/browse/gvfs/tree/po/de.po#n2015) is fitting both the message you stated and its German counterpart I saw here.
Clicking on "Applications" in "Places" view of the left column is [not] affected following the same pattern as this issue's actual problem. This has been a downstream problem in Ubuntu, see #87.
According to `ldd` binary `pcmanfm-qt` is linked against quite some binaries less than on Arch Linux or Fedora.

**Comment by jubalh** [comment]
Will take a look at it soon.
Not sure what "cornelisbb" comment has to do with it though, as it was about OBS settings and not about packaging.

**Comment by r-a-v-a-s** [comment]
I just built from source and it works.

**Comment by jubalh** [comment]
I have an older Laptop where installed Leap quite some time ago. I tested it there, and have the same error like you have. Even after doing a full distribution upgrade. I will have to investigate here a bit.

**Comment by r-a-v-a-s** [comment]
Here is everything I installed today for lxqt: http://pastebin.com/r9wyfP1z

**Comment by r-a-v-a-s** [comment]
Note that the installed version also works now.

**Comment by DimStar77** [comment]
The interesting package that is missing is "libfm" - and in there specifically the module called vfs_search - which makes search capability work for stuff relying on this library.

**Comment by agaida** [comment]
@DimStar77 - you are right, libfm is a runtime dependency - packagers should mention it - people who build the packages themself should know that :D

**Comment by DimStar77** [comment]
@agaida - in openSUSE, the library (libfm.so.4) is represented as a dependency in the package, but not the various libfm modules - which is what leads to the error described here... I trust @jubalh will be fixing this up soon

**Comment by agaida** [comment]
@DimStar77 - right, we had this packaging bug in debian too (missed modules i guess) - or i encountered before in siduction, but i'm pretty sure, that i was hit by this too

**Comment by jubalh** [comment]
@r-a-v-a-s thanks for bringing this to our attention
@DimStar77 thanks for fixing it :)

**Comment by pmattern** [comment]
> @DimStar77 thanks for fixing it :)

And what exactly do you think is fixed?
I'm still seeing the problem here on Tumbleweed running PCManFM-Qt from its main repository (main repo of Leap 42.1 provides 0.9 which doesn't feature the search yet) as well as on Tumbleweed and Leap 42.1 running PCManFM-Qt from repository `X11:LXQt` installed like this
```
# zypper ar http://download.opensuse.org/repositories/X11:/LXQt/openSUSE_{Tumbleweed,Leap_42.1}/X11:LXQt.repo
# zypper update
# zypper install -t pattern LXQT
```
If this shouldn't be the right way to install please let me know.

But maybe we should first clarify some other things:
> `X11:LXQt` [...] is a devel project for Factory

So could you kindly explain why [this page](https://build.opensuse.org/project/repositories/X11:LXQt) is linking to packages that are obviously geared towards openSUSE Leap 42.1?

> openSUSE Leap not having the version of Qt needed to build the LXQt from `X11:LXQt`

Given that the said packages are indeed geared towards openSUSE Tumbleweed and Leap 42.1 the packages have to get adjusted to the distribution not the other way around.
openSUSE Leap 42.1 was including Qt 5.5 right from the beginning so it's not plausible at all that it should ever have shipped a Qt version not suitable to compile LXQt.

Missing components of `libfm` due to the way it's packed can sure be a reason of this problem yet I doubt it's to blame. The problem ceases when PCManFM-Qt gets built locally, either from its sources without any packaging or by running `ocs build` in a local checkout from `X11:LXQt`.
To me this still looks like package pcmanfm-qt just need to be rebuilt on a current system.

Btw., you are aware that pattern `LXQt` can't be installed without manual intervention as it depends on a package `obconf-qt` which isn't available at all right now?

**Comment by DimStar77** [comment]
Of course it works after you build it locally, because, in otder to do so, you install libfm-devel, which in turn pulls in libfm...

in fact, you'd not even have to build it locally - once you have all the deve installed, reboot your system and guess what: it will be working already.

> sudo zypper in libfm-devel
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 8 NEW packages are going to be installed:
  **libfm** libfm4 libfm-devel libfm-extra4 libfm-extra-devel libfm-gtk4 libfm-lang libmenu-cache3

**Comment by pmattern** [comment]
Installing libfm is indeed fixing the problem.
Development packages are not needed (why should they, this is not about re-compiling any longer) neither is rebooting but restarting PCManFM-Qt is enough. A bit tricky to discover, IMO, as the output of `ldd` suggests everything is fine even when the problem is manifest.

Btw. this
> And what exactly do you think is fixed?

was aimed at @jubalh. In order to be called "fixed" it can be expected the problem is no longer manifest after a regular installation. But no dependencies have been adjusted so far.

**Comment by DimStar77** [comment]
> Installing libfm is indeed fixing the problem.
> Development packages are not needed (why should they, this is not about re-compiling any longer) 

Agreed - my pasting the comment about libfm-devel was trying to explain why it works for the users 'when they locally built' - because they happened to install the package in question.

As for what is fixed: *I* submitted the fix for openSUSE Tumbleweed (https://build.opensuse.org/request/show/399601) - it's up to the libfm maintainer to decide if this fix is worthy to be submitted to openSUSE Leap 42.1 as a maintenance update or not.

**Comment by pmattern** [comment]
> Agreed - my pasting the comment about libfm-devel was [...] package in question.

Sure. I was already assuming this but didn't mention in order to keep my comment rather short.

> As for what is fixed: I submitted the fix for openSUSE Tumbleweed (https://build.opensuse.org/request/show/399601)

Arrrgh. Why didn't he mention this above but said thanks *to you* instead?! This would have avoided a lot of confusion.
In case the request gets rejected I'd strongly suggest you make package pcmanfm-qt depend on libfm. It's a rather essential feature that lacks otherwise.

Also, from the point of view of a user not too familiar with openSUSE I'd say the package descriptions of `libfm{,4}` deserve some polish. The output of `zypper info libfm{,4}` isn't exactly helpful to figure out what are the differences between these to packages to say the least.

By "regular installation" I was thinking of the packages in project / repository `X11:LXQt` anyway, not of Leap 42.1. Am I right by assuming the packages of this project are the basis of the packages in the main repositories of both Tumbleweed and the stable distributions like currently Leap?
