### ISSUE TITLE
Thumbnails conformity to XDG Thumbnail Managing Standard

### ISSUE THREAD

**Issue by ivan-abdulin** [lxde/pcmanfm-qt#436]
PCManFM stores thumbnails in $HOME/.thumbnails. According to XDG [standart](https://specifications.freedesktop.org/thumbnail-spec/thumbnail-spec-latest.html#DIRECTORY) it should store it in "$XDG_CACHE_HOME/thumbnails" or "$HOME/.cache/thumbnails" if first variable is not set.

I presume, this is the [place](https://github.com/lxde/libfm/blob/b08218e2311dc52465ef92502061738701f298c1/src/base/fm-thumbnail-loader.c#L749) where default thumb dir is set.

Unfortunately, I'm do not know qt/cpp to send PR (even if it would be that simple).

**Comment by tsujan** [comment]
Thanks for mentioning it!

However, apart from not following some standards, does pcmanfm-qt have any *practical* problem in showing thumbnails?

**Comment by ivan-abdulin** [comment]
None on my desktop. You could probably set the priority of this to lowest one.

**Comment by tsujan** [comment]
Thanks! I asked because gdk-pixbuf2-2.36.1 has a bug that may cause problem in creating thumbnails -- I thought you'd encountered that bug.

BTW, libfm is written completely in C and is based on GLib.

**Comment by tsujan** [comment]
Has anyone -- and especially Arch users with gdk-pixbuf2 >= 2.36.1 -- encountered problems about png thumbnails (of new screenshots, for example)? Recently, my newly created png files started to have broken thumbnails and the problem was fixed only after I removed "/usr/share/thumbnailers/gdk-pixbuf-thumbnailer.thumbnailer" (neither this file nor the binary gdk-pixbuf-thumbnailer existed before). Why do recent versions of gdk force their (buggy) thumbnailers?! A new Gnome "policy"?

**Comment by jleclanche** [comment]
This was fixed this release (in https://github.com/lxde/libfm-qt/commit/6c7831f10ea3d61b8872ca5c8dc1ff8dbfdf022c to be precise)

**Comment by felixsanz** [comment]
@tsujan @jleclanche 

why close this issue? it wasn't about that bug, it was about following XDG specifications, which is still valid. Can you please re-open it and consider fixing it?

Thanks

**Comment by tsujan** [comment]
@felixsanz 
Thumbnails ARE in `$XDG_CACHE_HOME/thumbnails`.

**Comment by felixsanz** [comment]
@tsujan I'm so sorry, googled it and didn't notice this was -qt version xd
