### ISSUE TITLE
Header of listview's owner column may be cut

### ISSUE THREAD

**Issue by excalibur1234** [lxde/pcmanfm-qt#461]
http://s18.postimg.org/jayo5o9bt/screen.png

as you can see in the screenshot, the default column width is always too wide. the "name" column is just a little too wide pushing the "owner" column to the right.
this is happening to me for many months. pcmanfm-qt is reset to that width after closing and opening.

it looks like https://github.com/lxde/pcmanfm-qt/pull/230 did not consider all edge cases. can anybody confirm this visual bug or is it just me?

**Comment by tsujan** [comment]
It's logical to make the name column the largest because names could be long, while other info usually have fixed widths.

However, as is reported here, *only* when the owner name is too short (like "root"), the *header* of the owner column is cut. Since the reporter's screenshot isn't available, I attach one:

![owner_colimn](https://user-images.githubusercontent.com/981076/30496618-3bea2328-9a65-11e7-869e-dac12e72e573.png)

**Comment by tsujan** [comment]
Sorry, I was wrong about the screenshot not being available. Both screenshots show the same thing, as mentioned above.

**Comment by tsujan** [comment]
The fix is here: https://github.com/lxde/libfm-qt/pull/115
