### ISSUE TITLE
Two (same) devices shown upon mounting a loopback device 

### ISSUE THREAD

**Issue by palinek** [lxde/pcmanfm-qt#501]
By mounting an ISO by simply `mount -o loop foo.iso bar` there are sometimes 2 devices with the same name shown in the 'Places' pane.

##### Expected Behavior

Show only one device.

##### Current Behavior

Sometimes one device is shown and sometimes 2, but only the first one is selectable/unmountable.

##### Steps to Reproduce (for bugs)

1. run pcmanfm-qt
2. mount an iso by `mount -o loop foo.iso bar`
3. observe the device(s) addition
4. 

##### System Information

* Distribution & Version: debian testing with lxqt snapshots
* Kernel: 4.9.0-2-amd64
* Qt Version: 5.7.1
* Package version: 0.11.4~22-g015909c-1

**Comment by tsujan** [comment]
Confirmed. (Sorry for the late reply!)

**Comment by tsujan** [comment]
The problem is that when GLib emits "mount-added", Qt may not be ready to check items (the view may not be refreshed yet) and see that there *is* and item for the `GVolume` in question. a `singleShot()` with a non-zero interval solves the problem but it isn't a real solution. Still searching for a good fix....

**Comment by tsujan** [comment]
The above statement was wrong (although `singleShot` worked for another reason). Long story short, the correct explanation is included in the PR: https://github.com/lxde/libfm-qt/pull/133.
