### ISSUE TITLE
LXQt file dialog may be needed

### ISSUE THREAD

**Issue by tsujan** [lxde/pcmanfm-qt#551]
##### Expected Behavior
KDE has its file dialog; LXQt may need its own.

##### Current Behavior
Currently, LXQt uses the default Qt file dialog, which lacks features like showing thumbnails, scrolling to the current file, showing hidden files with `Ctrl+H`, etc.

**Comment by palinek** [comment]
And the newly implemented dialog should be based on libfm-qt?

**Comment by luis-pereira** [comment]
Isn't `lxqt-qtplugin` implementation of [QPlatformDialogHelper::createPlatformDialogHelper](https://github.com/lxde/lxqt-qtplugin/blob/master/src/lxqtplatformtheme.h#L51) the right place to do it ?

**Comment by tsujan** [comment]
> And the newly implemented dialog should be based on libfm-qt?

@palinek, yes, because of thumbnails at least.

> Isn't lxqt-qtplugin ... the right place to do it ?

@luis-pereira, yes, I think it is the place.

**Comment by PCMan** [comment]
I'm willing to take this one.
It's in my TODO list long time ago but I never really worked on it.
This week I might have some spare time, so please let me give it a try. :-)

**Comment by tsujan** [comment]
> I'm willing to take this one.

That would be great! Wrestling with a few unreproducible bugs, I may not be able to work on it soon.

**Comment by PCMan** [comment]
Work in progress. :-)
![filedialog_wip](https://user-images.githubusercontent.com/46543/28745792-54bcbc2c-74b2-11e7-831d-e84e8bc32ffe.png)

**Comment by tsujan** [comment]
> Work in progress. :-)

With a setting and a pane for showing thumbnails, it'll be perfect.

**Comment by tsujan** [comment]
Or thumbnails could be shown as they are in pcmanfm-qt -- not in a pane -- in which case, a setting for the icon size will be needed.

**Comment by tsujan** [comment]
And a filer-bar, or it can be added later... sorry for the babble...

**Comment by PCMan** [comment]
@tsujan @palinek @luis-pereira 
So unfortunate!!! After some initial attempt to implement this with the new Fm::FileDialog, I realize that it does not work.
The file dialog can be shown, but because of the modality, all Qt widgets are disabled during the execution of the file dialog, including the file dialog itself.
The original design of this platform interface is used to support platform native dialogs which are non-Qt widgets and not controlled by Qt event loop. So Qt can safely disable all Qt widgets and hand over the control to the platform native file dialog which runs inside its own platform native event loops not controlled by Qt.
When the platform plugin is also implemented using Qt, the file dialog is also disabled at the same time and does not respond to user input. There is no way to override the window modality stuff in Qt.

The simplest workaround I can think of is moving the file dialog to its own process and let it runs its own event loop outside the parent process. Then, let the platform helper plugin communicate with it via IPC.

**Comment by palinek** [comment]
> The simplest workaround I can think of is moving the file dialog to its own process and let it runs it own event loop outside the parent process. Then, let the platform helper plugin communicate with it via IPC.

You suggested that as the "non-naive" way, not?

**Comment by PCMan** [comment]
Adding IPC here adds much more complexity so as a proof of concept, I directly call libfm-qt from lxqt-qtplugin first and found that it does not work due to the aforementioned reason. So I'll start investigating how to do it correctly with IPC.
As a side-effect, the service can become "optional" and lxqt-qtplugin can have no hard dependency on it since they are different programs. At runtime, turn on the feature if the file dialog service exists.

**Comment by tsujan** [comment]
Shouldn't we see how KDE does it and if its way is usable to use?

**Comment by PCMan** [comment]
@tsujan Good idea. Found a workaround in KDE code.
https://github.com/KDE/plasma-integration/blob/master/src/platformtheme/kdeplatformfiledialoghelper.cpp

**Comment by PCMan** [comment]
OK, PR is here.
https://github.com/lxde/lxqt-qtplugin/pull/23

**Comment by tsujan** [comment]
@PCMan So fast! I was digging into KDE sources for an hour.

**Comment by tsujan** [comment]
Beautifully done by @PCMan. Closing.
