### ISSUE TITLE
Better multiple rename

### ISSUE THREAD

**Issue by sammoth** [lxde/pcmanfm-qt#597]
Hello, at the moment if you select lots of files and try to rename them, you get one popup for each file asking for a new name, one after the other. This isn't very useful and is especially bad if you select a large number of files mistakenly and then have to hold the escape key until all the popups disappear.

Thunar has the best functionality in this case, and Dolphin's is also good. Both allow renaming using sequential numbers, and Thunar has more features still.

At least I think choosing Cancel should prevent the remaining popups from appearing so that you do not have to cancel each one.

libfm 1.2.5
libfm-extra 1.2.5
libfm-qt 0.12.0.2
pcmanfm-qt 0.12.0

**Comment by tsujan** [comment]
Yes, a third button (Cancel All) is needed. Also, Dolphin's behavior is worth considering.

**Comment by tsujan** [comment]
I'll try to implement something like this:

![rename_dolphin](https://user-images.githubusercontent.com/981076/32698625-d44da254-c7bd-11e7-81a9-631edeced62b.png)

**Comment by tsujan** [comment]
On second thought, I just made the Cancel button really cancel the renaming; the PRs are https://github.com/lxde/libfm-qt/pull/130 and https://github.com/lxde/pcmanfm-qt/pull/598. If the user wants to skip a file, he/she could just press OK/Enter without changing the name.

The reason is that, practically, "Bulk renaming" is quite different from multiple renaming and shoudn't replace it. As you can see in the above screenshot, Dolphin doesn't select the real file name and that's bad. However, an extra item could be added to pcmanfm-qt's Edit menu for "Bulk renaming" at some point. I'll think about it later; let's have an appropriate multiple renaming for now!

**Comment by tsujan** [comment]
Opened https://github.com/lxde/pcmanfm-qt/issues/599.
