### ISSUE TITLE
CFLAGS or CPPFLAGS are ignored

### ISSUE THREAD

**Issue by Hi-Angel** [lxde/pcmanfm-qt#627]
I wanted to take a look [at this issue](https://github.com/lxde/pcmanfm-qt/issues/620), but my attempts in making a debug build result in quitting with lots of errors `CMakeFiles/pcmanfm-qt.dir/application.cpp.o: plugin needed to handle lto object`. Upon closer inspection the reason appears that I have the following flags set:

	$ grep FLAGS /etc/makedebugpkg.conf
	# ARCHITECTURE, COMPILE FLAGS
	CPPFLAGS="-fno-lto -O0 -g3"
	CFLAGS="-fno-lto -O0 -g3"
	CXXFLAGS="-fno-lto -O0 -g3"
	LDFLAGS="-fno-lto -Wl,--sort-common,--as-needed,-z,relro"

However the build ignores CPPFLAGS and CFLAGS, and only handles LDFLAGS.

Steps to reproduce:

1. `export CPPFLAGS="-fno-lto -O0 -g3"`, `export CFLAGS="-fno-lto -O0 -g3"`, and `export LDFLAGS="-fno-lto -O0 -g3"`
2. run the build
3. See the build failing on link stage; can be also seen explicitly as:
	```
	$ strings src/build/pcmanfm/CMakeFiles/pcmanfm-qt.dir/application.cpp.o | grep -e -O   
	t-O}m
	NH-Ok-
	D-OI
	'-fmath-errno' '-fsigned-zeros' '-ftrapping-math' '-fno-trapv' '-fno-openmp' '-fno-openacc' '-dD' '-mtune=generic' '-march=x86-64' '-O0' '-O0' '-O3' '-fvar-tracking-assignments' '-fno-exceptions' '-flto' '-fuse-linker-plugin' '-fvisibility=hidden' '-fPIC'
```

**Comment by tsujan** [comment]
> I wanted to take a look at this issue...

It doesn't seem to be a real issue.

As for a debug build, I always use the standard method in Arch and encounter no problem. Unfortunately, I have no idea about the problem you've encountered. @luis-pereira, @agaida ?

**Comment by agaida** [comment]
i tend to close this without a second view - my glassballs and the black cat are on hollidays, the cauldron is not even fired up - damn, i'm don't willing to put any time on that when a "bug" reporter don't spend the time to fill out some really simple questions - and sorry, if the questions are to hard there is nothing we can do, even if we want to.

**Comment by Hi-Angel** [comment]
@agaida what are you talking about?

**Comment by Hi-Angel** [comment]
@agaida did you try to reproduce the steps I filled and they didn't work?

**Comment by agaida** [comment]
Why should i - for me the so called report isn't valid

**Comment by Hi-Angel** [comment]
@agaida dude, I don't know who you're, but with the attitude you show I definitely don't want to put any time on your project. I gave you 3 simple steps. You started mocking me, and didn't even tried to elaborate what's wrong.

I'm closing it. Good luck.

**Comment by agaida** [comment]
only a hint for reporting bugs: If there is a simple form - be so kind and fill in at least some basic things - it is not nice to assume that people get their needed informations by klicking through several maybe chained bug reports.
second: use the distribution standard methods

**Comment by Hi-Angel** [comment]
@agaida don't you see this is ridiculous? I just looked over the template, and the only relevant information I missed is "Distribution". Kernel and libs is irrelevant because I'm complaining about build system. Context is obvious from the summary. Actual behavior is at least in damn title! Expected behavior is obvious from the actual behavior.

You started mocking on me for no reason. Now, how do you feel if I say that I don't like two types of people: those who can't read and those who can't think, and for some reason it's unpleasant for me to talk with you. Don't you like when people mock on you, huh??

**Comment by tsujan** [comment]
> @agaida don't you see this is ridiculous?

You would know that it isn't so if you were a little objective. You expected a magic and I called @luis-pereira and @agaida, thinking that they might have one. I didn't and, apparently, they didn't either.

**Comment by Hi-Angel** [comment]
@tsujan I surely don't see what part did I wrote confusingly. I can think of only the step 3 where I did not mention the build command because cmake + make would take a bit too much space whereas there's no other way to build till link stage anyway. I did test the steps by exporting variables, so I know it works with either `cmake . && make` or `makepkg --config myconfig` which in turn calls cmake'n'make.

**Comment by tsujan** [comment]
@Hi-Angel If your goal is making a debug build, you could consult the docs of your distro. I mentioned Arch above; Debian has its own method; and so on. If you expected me to understand your report, I'd say, "sorry, I don't." If that's ridiculous, let it be so!

**Comment by Hi-Angel** [comment]
@tsujan how is my distro even relevant? There is standard method of assigning `*FLAGS` on command line, and whatever distro I'm running for that absolutely doesn't matter.

What if I run my own `hi-angel-super-distro` and I didn't write the documentation for making debug builds?

**Comment by tsujan** [comment]
> There is standard method of assigning *FLAGS on command line, and whatever distro I'm running for that absolutely doesn't matter.

Obviously, when we can make debug builds in Arch and Debian, something should be wrong with the way *you* use "standard methods" and that can't be out problem.

**Comment by agaida** [comment]
and for debian thats dead easy:
``` ~/work/code/pkg-main/pcmanfm-qt/snapshot (git)-[experimental-snapshots/latest] % cat debian/rules 
#!/usr/bin/make -f
# export DH_VERBOSE=1

export LC_ALL=C.UTF-8
export DEB_LDFLAGS_MAINT_APPEND = -Wl,--as-needed
export DEB_BUILD_MAINT_OPTIONS = hardening=+all

%:
        dh ${@} --buildsystem cmake --with quilt

override_dh_auto_configure:
        dh_auto_configure --\
                -DPULL_TRANSLATIONS=OFF\
                -DUPDATE_TRANSLATIONS=OFF\
                -DCMAKE_BUILD_TYPE=RelWithDebInfo
```
thats all the magic i use

**Comment by tsujan** [comment]
> and for debian thats dead easy:

And for Arch that's much easier ;)

**Comment by agaida** [comment]
:( - i find it easy :D

**Comment by Hi-Angel** [comment]
For any future readers — the solution was to explicitly use `export CXXFLAGS` instead of `export CPPFLAGS`. Why this doesn't work with `makepkg` — who knows.

**Comment by luis-pereira** [comment]
@Hi-Angel The solution makes sense.
`CPPFLAGS` are extra flags to give to the C preprocessor and programs that use it (the C and Fortran compilers).
`CXXFLAGS` are extra flags to give to the C++ compiler.

**Comment by eli-schwartz** [comment]
In fact, makepkg runs the following logic after sourcing your makepkg.conf, in order to set up the environment (because there is no r eason for makepkg to set up CPPFLAGS and ignore CXXFLAGS, that would be quite stupid in fact).

`export CPPFLAGS CFLAGS CXXFLAGS LDFLAGS MAKEFLAGS CHOST`

So I am completely baffled as to how you can possibly show that makedebugpkg.conf and then say that makepkg is ignoring CXXFLAGS and you had to manually export them yourself. I'd also like to offer the following piece of advice, that if you are changing your CFLAGS you are doing it all wrong -- makepkg by default strips all packaged binaries, so your debug build won't do you any good unless you turn that off. But then you might as well enable the debug option, which... already appends DEBUG_CXXFLAGS to CXXFLAGS.

So instead of maintaining multiple makepkg configuration files in order to toggle debug builds, you should just edit the PKGBUILD and add `options=(debug)`.

...

Just offered FWIW, as you seem to really be messing up makepkg.

**Comment by Hi-Angel** [comment]
@eli-schwartz thanks for advice. I am not using `DEBUG_CXXFLAGS` on purpose — the first time I tried making debug build I went with them, and it resulted in some problems. I unfortunately don't rememeber offhand the details, but I remember that back reporting a bug to `pacman` project, which then was closed as NOTABUG with somewhat harsh explanation along the lines *"debug builds are on supported on Archlinux and it will never change"*, and then I remember finding a way through `--config` option, and then even editing an Archlinux wiki so that people could use that solution too.

> makepkg by default strips all packaged binaries

This is untrue, I've been using this technique for a long time. E.g. right now I have `/usr/lib/libpurple.so` built this way, and I checked — it does have debug symbols.

> So I am completely baffled as to how you can possibly show that makedebugpkg.conf and then say that makepkg is ignoring CXXFLAGS and you had to manually export them yourself

Yeah, I'm curious too. I have a hypothesis that for that to work I should've changed in my makepkg.conf `CXXFLAGS=` to `export CXXFLAGS` because behavior differs a bit. I didn't do this because that's how it was there by default, and the defaults might be because otherwise running makepkg would result those flags to "stuck" in the environment.

That's just a hypothesis though, I'm not really interested in checking it, well, not now at least.

**Comment by eli-schwartz** [comment]
> am not using DEBUG_CXXFLAGS on purpose — the first time I tried making debug build I went with them, and it resulted in some problems. I unfortunately don't rememeber offhand the details, but I remember that back reporting a bug to pacman project, which then was closed as NOTABUG with somewhat harsh explanation along the lines "debug builds are on supported on Archlinux and it will never change",

This is sufficiently vague that I have no idea what you are talking about. Links or it didn't happen.

pacman itself supports debug builds just fine, why do you think there is an option for it in the first place? 

> This is untrue, I've been using this technique for a long time. E.g. right now I have /usr/lib/libpurple.so built this way, and I checked — it does have debug symbols.

Well, yeah -- you changed the defaults. So change some more defaults, and do things, the nice, simple, proper, and easy way.



> Yeah, I'm curious too.

I'm not curious at all, I know for a fact you are wrong and don't need to investigate further.

> I have a hypothesis that for that to work I should've changed in my makepkg.conf CXXFLAGS= to export CXXFLAGS because behavior differs a bit. I didn't do this because that's how it was there by default, and the defaults might be because otherwise running makepkg would result those flags to "stuck" in the environment.

The behavior is not different. makepkg covers your back by running `export` just in case you forgot to, and as a result it is completely extraneous to do so yourself. You can do it if you want, but it makes no difference -- makepkg "stuck" it in the environment already, it doesn't matter how many times you "stuck" it again, it is still exported.

You must have done something completely different to break this. I don't know what it is, and I'm not sure I care either -- the only reason I popped in here was to correct some wrong information about makepkg, which I have now done. The pcmanfm-qt developers can help you debug your pcmanfm-qt issues, assuming they are still interested since the steps you documented are clearly wrong.

**Comment by Hi-Angel** [comment]
> This is sufficiently vague that I have no idea what you are talking about. Links/logs or it didn't happen.
> 
> pacman itself supports debug builds just fine, why do you think there is an option for it in the first place?

Fair enough. Here's [my modification to Archlinux Wiki](https://wiki.archlinux.org/index.php?title=Debug_-_Getting_Traces&diff=prev&oldid=451454), and [here's according pacman bug](https://bugs.archlinux.org/task/50861).

> Well, yeah -- you changed the defaults. So change some more defaults, and do things, the nice, simple, proper, and easy way.

I don't see how experiencing the bug behavior is better and nice.

> I'm not curious at all, I know for a fact you are wrong and don't need to investigate further.

lol ok. Then why have you even started?

> You must have done something completely different to break this. I don't know what it is, and I'm not sure I care either -- the only reason I popped in here was to correct some wrong information about makepkg, which I have now done.

I must have missed something, what was that "wrong info" you just corrected?

> The pcmanfm-qt developers can help you debug your pcmanfm-qt issues, assuming they are still interested since the steps you documented are clearly wrong.

Care to elaborate in what way are they wrong?

**Comment by eli-schwartz** [comment]
> somewhat harsh explanation along the lines "debug builds are not supported on Archlinux and it will never change",

I see. Because your proposed changes would prevent Arch Linux from creating debug packages should we wish to do so (and we do wish to do so, but our dbscripts tools are currently unable to handle putting debug packages in a separate debug repository and therefore we have disabled this), you decide that instead, what we actually said was "Hahaha, we will never provide debug builds ever, plus screw you if you want to use makepkg to compile your own debug packages, neener neener neener".

I was right to call you out on that, because you've gone from ridiculous to mendacious.

> I don't see how experiencing the bug behavior is better and nice.

I don't see a bug. Optimizations don't stop you from receiving debug output, you decided that you value lots and lots of optimizations, and quite frankly DEBUG_C*FLAGS doesn't stop you from using -Og anyway.

**Comment by Hi-Angel** [comment]
> "Hahaha, we will never provide debug builds ever, plus screw you if you want to use makepkg to compile your own debug packages, neener neener neener".
> 
> I was right to call you out on that, because you've gone from ridiculous to mendacious.

You didn't read comments on the bug, did you? What I said is written in the first comment by the maintainer. You weren't right to call me on this.

> I don't see a bug. Optimizations don't stop you from receiving debug output, you decided that you value lots and lots of optimizations, and quite frankly DEBUG_C*FLAGS doesn't stop you from using -Og anyway.

Did you ever try debugging an optimized package? It is very bad, it's almost the same as debugging a package with no debugging symbols at all. Pretty much everything in gdb results in `optimized out` message. Besides, the only thing you could trust to is stacktrace — now, if you consider that I am *(as, I'm sure, lots of peoples)* using `-flto` in my optimized builds, you can't trust even the stacktrace.

**Comment by eli-schwartz** [comment]
Not only did I read Allan's comment, but I also replied to that bug in order to tell you exactly what you should have done instead of filing that bug.

Also your Arch Wiki advice has been rejected as well, ho hum. https://wiki.archlinux.org/index.php?title=Debug_-_Getting_Traces&diff=next&oldid=464091

Basically, your misguided attempt to mangle the Arch Linux build system in ways that I don't fully understand and you haven't fully described has somehow, I'm not sure how, managed to prevent CXXFLAGS from even existing in the first place, because none of your results make sense (which is exactly the kind of issue I expect to arise when people don't understand what they're using), and thereby tricked you into accusing upstream software of not respecting CXXFLAGS. Or at least that is the only likely conclusion I can draw from here.

**Comment by Hi-Angel** [comment]
> Not only did I read Allan's comment, but I also replied to that bug in order to tell you exactly what you should have done instead of filing that bug.

How cute, I replied back.

But this doesn't matter, you paraphrased me and called "mendacious" even though it was the content of the first comment. After that, you're mendacious, how about that?
 
> Basically, your misguided attempt to mangle the Arch Linux build system in ways that I don't fully understand and you haven't fully described has somehow, I'm not sure how, managed to prevent CXXFLAGS from even existing in the first place, because none of your results make sense (which is exactly the kind of issue I expect to arise when people don't understand what they're using), and thereby tricked you into accusing upstream software of not respecting CXXFLAGS. Or at least that is the only likely conclusion I can draw from here.

How did it happened you put in the same paragraph `ways that I don't fully understand` and the implication that I don't understand what I'm doing? Don't tell me that. I understand what I'm doing very well. 

> Also your Arch Wiki advice has been rejected as well, ho hum. https://wiki.archlinux.org/index.php?title=Debug_-_Getting_Traces&diff=next&oldid=464091

Oh, well. You know what, I am not surprised. Though I like GNU/Linux, but I definitely should stop social contribution attempts. Because pretty much all my social contacts ends up like this, in people not understanding me, and me not understanding what don't they understand, and then people starting to fight with me if I'm trying to dig deeper.

**Comment by tsujan** [comment]
> Because pretty much all my social contacts ends up like this, in people not understanding me, and me not understanding what don't they understand...

Read this, supposing that a friendly voice says it -- it doesn't hurt:

Logically, what you said above is a sign. You could interpret it as a sign of something in all other people you interact with, or you could consider it as a sign of something in yourself. The first option makes any change impossible because others are out of your control.

**Comment by Hi-Angel** [comment]
> Logically, what you said above is a sign. You could interpret
> it as a sign of something in all other people you interact
> with, or you could consider it as a sign of something in
> yourself. The first option makes any change impossible because
> others are out of your control.

You see, when I complain about something alike, the suggestion "have you considered it could be something wrong with you?" is always the first. Of course I did 😄 I do indeed have an indirect problem — from my experience I see patterns around me somewhat better than others. Up to the point that I see them in places where they don't really exist. This results in me being a good as a researcher but very bad socially, just because actions from an interlocutor in my mind often results in explosion of possible causes and I can't ever know which one is the  real — they all looks plausible!

Fortunately we're on the Internet, so I don't need to watch out for emotional part, and can concentrate just on discussion. But you see, I still have problems 😄

I started thinking, maybe it's me omitting details an interlocutor doesn't know, so I started giving as much info as I can in communication. Verbally, usually peoples don't like listening to lots of info, so I got used to talking very fast. As for the Internet, since my fast talking abilities doesn't matter, I started trying to cut down the info in a way stuff can be easily derived from. I think, trying to compress information worked well in general, but it usually needs some time to re-read the text, so not really applicable in verbal communication. Talking very fast in verbal communication didn't work so good, people seems to just stop listening me.

Is it a problem with me? I don't know, maybe. The issue is that I don't see what that problem could be if any. I feel like all I'm doing are workarounds for something I'm lacking, but my attempts to see what is that I'm lacking are akin to application a group operation within a mathematical group in attempts to get an element out of the group, i.e. a pointless Sisyphus' work *(I am sorry for real stupid analogy, but I feel real sleepy for coming up with better analogies, and I shouldn't sleep for at least 8 hours more to restore my sleep period)*.

-----

It would be wrong to say though I did not understand that what I was having with **eli-schwartz** was not a technical discussion but rather a word fight.

That's it I think. I don't know what else to say.

**Comment by Hi-Angel** [comment]
@tsujan to elaborate, I actually appreciate your help, and if you turn out to come up with some advises, I'll appreciate hearing them.

**Comment by tsujan** [comment]
@Hi-Angel 

We appreciate all bug reports if they are really clear and are really *bug reports*. Mistakes are tolerated, of course.

Considering the mind set you showed here, I have only one advice: When you open an issue about pcmanfm-qt or libfm-qt, see me as a stupid person who needs a very clear and *step-by-step* way of reproducing the bug in question. You might be good at mind reading but I'm not.
