### ISSUE TITLE
Align icons to grid on desktop

### ISSUE THREAD

**Issue by paulolieuthier** [lxde/pcmanfm-qt#97]
There should be an option for that.

**Comment by PCMan** [comment]
This will change the UI. Leave this for 1.0.

**Comment by pmattern** [comment]
Issue was fixed in the wake of lxde/pcmanfm-qt#252.

As discussed in this PR a remnant that may eventually still need to be addressed is a missing means to adjust the distance of objects on the desktop (that is to adjust the grid which is used right now).
But this is already addressed in lxde/lxqt#786.

**Comment by pmattern** [comment]
Using a grid was introduced *as default behaviour* in lxde/pcmanfm-qt#252 solving several issues like multiple selection by clicking single objects.

So strictly speaking (and unlike I thought when closing) this issue is not fixed yet if aligning to a grid should be *optional*.

On a side note a related finding that eventually still needs to get addressed is a missing means to adjust the distance of objects on the desktop (that is to adjust the grid which is used right now).
This is already addressed in lxde/lxqt#786.

**Comment by tsujan** [comment]
@pmattern 
I can't say that unaligned desktop icons are impossible to manage but, their ugliness aside, do they have any advantage?

**Comment by pmattern** [comment]
@tsujan 
I'm not promoting anything here and personally I'd just be fine with a grid always being used.
Rather, I just wanted to briefly mention the impact of lxde/pcmanfm-qt#252 on this issue - and then to explain why closing was eventually premature.

**Comment by tsujan** [comment]
@pmattern 
OK! I just thought there might be an advantage I didn't know of.

**Comment by paulolieuthier** [comment]
I think it's safe to close. At least for me, unaligned icons are messy. Anyway, I think there is a issue with the grid on desktop: the grid does not stretch 100% vertically, and a gap is created in the bottom where you can't drag a icon to. This can be easy tested by using `Xephyr :1 -screen 800x600` to create a screen and then `DISPLAY=:1 pcmanfm-qt --desktop` to test pcmanfm-qt on it.

@tsujan can you reproduce it?

**Comment by tsujan** [comment]
@paulolieuthier 
If the gap's height is less than the grid cell height, it's OK. The cell height is a function of font/icon size and the screen height may not be an exact multiple of it. If not, please show a screenshot of the problem!

**Comment by paulolieuthier** [comment]
> If the gap's height is less than the grid cell height, it's OK.

That's exactly the case, and I understand my screen's height is not a multiple of the icon height. I just don't think it's OK. IMO, spacing must be added between the icons to remove the gap in the bottom.

**Comment by tsujan** [comment]
> spacing must be added between the icons to remove the gap in the bottom.

That seems to be a good idea. Since pcmanfm-qt *partly* uses size settings of libfm-qt, I should see if the implementation of this idea is possible without changing the latter. It might be a lot of work but I'll consider it. Thanks for the suggestion!

**Comment by paulolieuthier** [comment]
Thanks!

**Comment by tsujan** [comment]
@paulolieuthier 
OK, I succeeded in implementing your idea but to see if it's worth a PR (2 PR's, in fact), I should know the approximate value of this integer in your case: `(BOTTOM_GAP_HEIGHT - 12) / ICON_NUMBER_PER_COLUMN` because only if it's greater than 2, an extra vertical spacing will make sense.

Or you could just send a screenshot of your desktop when, at least, its first column is fully occupied by icons.

**Comment by paulolieuthier** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/1238157/12268732/bdaaaebc-b92c-11e5-9be2-aad37a845c3d.jpg)

**Comment by tsujan** [comment]
Thanks! Most of that gap will be covered -- only the 12-px default plus a few px will remain.

I'll make the PR's after more testing and considering various aspects of the changes, whose byproduct is the possibility of adding settings to pcmanfm-qt for spacing.

**Comment by paulolieuthier** [comment]
That's great news, thanks again. Just for curiosity, what is the 12px margin for?

**Comment by tsujan** [comment]
> what is the 12px margin for?

PCMan had considered a 12-px margin for the whole work area `(desktop - panel)` and I kept it.

**Comment by paulolieuthier** [comment]
:+1:

**Comment by tsujan** [comment]
@paulolieuthier What do you think about this algorithm:

*"If an extra icon can be added to the bottom by decreasing the vertical cell margin, do so; otherwise try to spread the icons to cover the bottom gap as far as possible!"*

The default cell margin is 3 px (which gives a 6-px spacing). Assuming a minimum of 1 px for the margin and judging by your screenshot, I think you might get 24=6x2x(3-1) extra pixels at the bottom. I don't know if that's enough for an extra icon in your case; I just wanted to give a picture of the above algorithm for you (and anyone interested) to think about it.

In simpler words, it means: *"First try to tighten columns but if that doesn't help, try to spread icons!."*

**Comment by paulolieuthier** [comment]
I think this sounds like a good idea. However, if the spacing will become an option in pcmanfm-qt, than we shouldn't change it to fit one more icon. Does it make sense?

In my screenshot, it looks like there is enough space for another icon, doesn't it? It's probably a matter of a few missing pixels for another icon to fit. If we spread the icons, they will probably be way too far. I think the right way to go is to keep the margin fixed, but smaller. With an option for the spacing, the user may increase it if he thinks the icons are too close (the option would set the minimum spacing).

What do you think?

**Comment by tsujan** [comment]
> However, if the spacing will become an option in pcmanfm-qt, than we shouldn't change it to fit one more icon

Exactly! Neither should we spread the icons.

A few hours ago, I tried the above method and got good results. In the image below, the left half shows desktop icons arranged as before, while the right half shows the same icons with the algorithm applied: one row is added at the bottom and there's no large gap anymore.

![comparison](https://cloud.githubusercontent.com/assets/981076/12282839/adefd670-b9b6-11e5-98d1-e974e93e45ff.png)

So far, so good. If a setting is added for margins, I'll set a condition in the code for this optimization to be used only with the default settings because when the user chooses a specific margin, he wants it unchanged -- as you mentioned.

**Comment by paulolieuthier** [comment]
Good results. I'm looking forward to it.

Just to make it clear: IMO there must never be a gap. The option would be to set the minimum spacing, to avoid getting the icons too close. But I guess this is a matter of taste.

**Comment by tsujan** [comment]
> The option would be to set the minimum spacing

OK, we'll discuss that when an option is added, perhaps under https://github.com/lxde/lxqt/issues/786 . For now, I try to optimize the code and do more testing.

**Comment by tsujan** [comment]
@paulolieuthier 
Sorry to bother you but, whenever you have time, could you test https://github.com/lxde/pcmanfm-qt/pull/294 (after installing libfm-qt with https://github.com/lxde/libfm-qt/pull/13) and see if the bottom gap is removed for you? There's no haste, of course.

**Comment by paulolieuthier** [comment]
Sure, I'll have some time tomorrow.

**Comment by paulolieuthier** [comment]
It's much better than in the previous screenshot! Nice work.

![screenshot](https://cloud.githubusercontent.com/assets/1238157/12352858/66df5108-bb68-11e5-92a6-65232230ff9d.png)

Little note: there is still a difference between the gaps in the bottom and top. What do you think about that?

**Comment by tsujan** [comment]
@paulolieuthier Thank you! I was going to ask you to add a screenshot but you already did :)

> there is still a difference between the gaps in the bottom and top

Desktop is bounded from below while the icons snap to the grid starting from above. On the other hand, to change the grid (cell) dimensions, we have to change its margins. So, we can change the height or width of all cells only by *even* numbers. Hence a bit of asymmetry is unavoidable. However, now the best use is made out of the available space.

If PCMan accepts the PR's, I'll start to work on spacing options after discussing some technicalities at lxde/lxqt#786.

**Comment by paulolieuthier** [comment]
Great.

**Comment by tsujan** [comment]
Closed by https://github.com/lxde/pcmanfm-qt/pull/294

**Comment by tsujan** [comment]
The margin option will be discussed at lxde/lxqt#786.
