### ISSUE TITLE
add custom commands to decompress/compress files

### ISSUE THREAD

**Issue by sixsixfive** [lxde/pcmanfm-qt#98]
unp is a simple perl script that can extract almost everything

https://packages.debian.org/source/sid/unp
https://screenshots.debian.net/package/unp

**Comment by AcarBurak** [comment]
Yes, this would be fine. Or atool for both compression and uncompression. Otherwise one is forced to use a gtk or kde archiver.

Yet, I could manage to create custom actions for atool. If sixsixfive is interested:

https://wiki.manjaro.org/index.php?title=CUSTOM_ACTIONS_FOR_PCmanFM-Qt#.E2.80.9CCompress.E2.80.9D_custom_action

**Comment by oouuppss** [comment]
Yes should be great to let user define their own app.
I use dtrx, just a shell  script
http://brettcsmith.org/2007/dtrx/

**Comment by sixsixfive** [comment]
rethink - custom commands would be nice

**Comment by tsujan** [comment]
That's already possible: custom actions inside '~/.local/share/file-manager/actions/' can do more than that -- they can include commands or call complex scripts from '~/bin/'. I use lots of them not only under LXQT but previously under Gnome and KDE.
The only problem I've found is in grouping custom actions under a sub-menu. PCManfm-qt doesn't do that correctly yet.

**Comment by tsujan** [comment]
> The only problem I've found is in grouping custom actions under a sub-menu

Fixed ages ago.
